version: '3'

services:
  redis:
    image: redis:latest
    container_name: Docker-Redis
    hostname: redis-db
    volumes:
      - /data
    restart: always
    ports:
      - 6379:6379
  backend:

    build: ./backend/
    container_name: Docked-Backend
    hostname: backend
    restart: always
    links:
      - redis
    env_file:
      - .env
    ports:
      - 8080:8080
  frontend:
    build: ./frontend/
    container_name: Docked-Frontend
    restart: always
    hostname: frontend
    env_file:
      - .env
    links:
      - backend
    ports:
      - 3000:3000


    
